#!/bin/bash
cp -rf ./2/horizon /usr/share/pyshared/
cp -rf ./3/openstack_auth /usr/share/pyshared/
cp -rf ./4/openstack-dashboard /usr/share/
cp -rf ./5/openstack-dashboard /etc/
cp -rf ./6/openstack_auth /usr/lib/python2.7/dist-packages/
cp -rf ./7/openstack-dashboard-ubuntu-theme /usr/share/
cp -rf ./1/horizon /usr/lib/python2.7/dist-packages/

service apache2 restart
mysql -u root -pcloud <<EOF 2>/dev/null
use nova;
alter table instance_types add column price double UNSIGNED ZEROFILL NULL DEFAULT NULL;
exit;
EOF

